# Generated by Django 6.0.5 on 2026-07-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_0007_alter_customuser_role_0007_profile_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tenant',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
