# Generated by Django 6.0.5 on 2026-08-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_bio_profile_date_of_birth_and_more'),
        ('tenants', '0003_tenant_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeeactivitylog',
            name='accounts_em_employe_f38059_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeactivitylog',
            name='accounts_em_tenant__5d6dd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeactivitylog',
            name='accounts_em_action_9375ff_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reset_password_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reset_password_token_created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.RemoveField(
            model_name='employeeactivitylog',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeactivitylog',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='EmployeeInvitation',
        ),
        migrations.DeleteModel(
            name='EmployeeActivityLog',
        ),
    ]
