# Generated by Django 6.0.5 on 2026-07-29 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_delivery_orderprescription_alter_invoice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_details',
            field=models.TextField(blank=True, help_text='Additional explanation required when the cancellation reason is Other.'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('ordered_by_mistake', 'Ordered by mistake'), ('wrong_address', 'Wrong delivery address'), ('wrong_product', 'Selected the wrong product'), ('no_longer_needed', 'Product is no longer needed'), ('found_better_price', 'Found a better price'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_restored',
            field=models.BooleanField(default=False),
        ),
    ]
