# Generated by Django 6.0.5 on 2026-07-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_delivery_address'),
        ('orders', '0014_delivery_orderprescription_alter_invoice_options_and_more'),
    ]

    operations = [
    ]
