# Generated by Django 6.0.5 on 2026-07-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_merge_20260715_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
