# Generated by Django 6.0.5 on 2026-08-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_cancellation_details_order_cancellation_reason_and_more'),
        ('orders', '0016_alter_order_delivery_address'),
    ]

    operations = [
    ]
